import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Hero from '../Components/Hero/Hero'
import SubHeroHeader from '../Components/SubHeroHeader/SubHeroHeader'
import { HeroContainer } from './index.style'
import { useEffect, useState } from 'react'
import { fetchQuery } from '../utils/fetchqueries'
import Slider from '../Components/Slider/Slider'
import Addresslocator from '../Components/Addresslocator'






const Home: NextPage = ({data}:any) => {




  return (
    <div>
      <Head>
        <title>Drinks Ahoy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroContainer>
        <Hero/>
      </HeroContainer>
      <SubHeroHeader/>
      <Slider data={data}/>
      <div style={{height:"15rem"}}></div>
      <Addresslocator/>

    
      
    </div>
  )
}
export const getStaticProps: GetStaticProps = async (context) => {

  const data = await fetchQuery('beers')

  return {
    props: {
      
      data

    },
    revalidate: 1,
  };



}




  
export default Home;