import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Hero from '../Components/Hero/Hero'
import SubHeroHeader from '../Components/SubHeroHeader/SubHeroHeader'
import { HeroContainer } from './index.style'
import { useEffect, useState } from 'react'






const Home: NextPage = ({beers}:any) => {


  console.log(beers)

  return (
    <div>
      <Head>
        <title>Drinks Ahoy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroContainer>
        <Hero/>
      </HeroContainer>
      <SubHeroHeader/>

    
      
    </div>
  )
}




  
export default Home;